version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          SHORT_COMMIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -8)
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: docker build ./client -t meetalodariya/client
      - run:
          name: "Build: Server"
          command: docker build ./server -t meetalodariya/server
      - run:
          name: "Build: Worker"
          command: docker build ./worker -t meetalodariya/worker
      - run:
          name: "Build: NGINX"
          command: docker build ./nginx -t meetalodariya/nginx

  deploy:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          SHORT_COMMIT_HASH: $CIRCLE_SHA1 | cut -c1-8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Push Images"
          command: |
          docker push meetalodariya/client |
          docker push meetalodariya/server |
          docker push meetalodariya/worker |
          docker push meetalodariya/nginx 


workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
