version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        command:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build-deploy:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Set environment var"
          command: |
            short_commit_hash=${CIRCLE_SHA1:0:8}
            echo 'export COMMIT_HASH="${short_commit_hash}"' >> $BASH_ENV
      # - run:
      #     name: "Build: Client"
      #     command: docker build ./client -t meetalodariya/client:${COMMIT_HASH}
      # - run:
      #     name: "Build: Server"
      #     command: docker build ./client -t meetalodariya/server:${COMMIT_HASH}
      # - run:
      #     name: "Build: Worker"
      #     command: docker build ./client -t meetalodariya/worker:${COMMIT_HASH}
      - run:
          name: "Build: NGINX"
          command: |
            echo "$COMMIT_HASH"
            docker build ./client -t meetalodariya/nginx:${COMMIT_HASH}
      - run:
          name: "Push images"
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker push meetalodariya/nginx:${COMMIT_HASH}
            fi

workflows:
  build-test-deploy:
    jobs:
      - test
      - build-deploy:
          requires:
            - test
