version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build-deploy:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build and save: Client"
          command: |
            docker build ./client -t meetalodariya/client
      - run:
          name: "Build and save: Server"
          command: |
            docker build ./client -t meetalodariya/server
      - run:
          name: "Build and save: Worker"
          command: |
            docker build ./client -t meetalodariya/worker
      - run:
          name: "Build and save: NGINX"
          command: |
            docker build ./client -t meetalodariya/nginx
      - run:
          name: "Push images"
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker push meetalodariya/client |
              docker push meetalodariya/server |
              docker push meetalodariya/worker |
              docker push meetalodariya/nginx
            fi

  # deploy:
  #   docker:
  #     - image: cimg/node:14.0.0
  #       auth:
  #         username: $DOCKERHUB_USERNAME
  #         password: $DOCKERHUB_PASSWORD
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 19.03.13
  #     - run:
  #         name: "Push Images"
  #         command: >-
  #           docker push meetalodariya/client |
  #           docker push meetalodariya/server |
  #           docker push meetalodariya/worker |
  #           docker push meetalodariya/nginx

workflows:
  build-test-deploy:
    jobs:
      - build-deploy
