version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          SHORT_COMMIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -8)
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build: Client"
          command: |
            echo "$SHORT_COMMIT_HASH"
            docker build ./client -t meetalodariya/client:$(SHORT_COMMIT_HASH)
      - run:
          name: "Build: Server"
          command: docker build ./server -t meetalodariya/server:$(SHORT_COMMIT_HASH)
      - run:
          name: "Build: Worker"
          command: docker build ./worker -t meetalodariya/worker:$(SHORT_COMMIT_HASH)
      - run:
          name: "Build: NGINX"
          command: docker build ./nginx -t meetalodariya/nginx:$(SHORT_COMMIT_HASH)

  deploy:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          SHORT_COMMIT_HASH: $CIRCLE_SHA1 | cut -c1-8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Push Images"
          command: echo "Pushing the images"

workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
