version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build-deploy:
    docker:
      - image: cimg/node:14.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build ./client -t meetalodariya/client
      - run:
          name: "Push images"
          command: |
            docker login -u="${DOCKERHUB_USERNAME}" -p="${DOCKERHUB_PASSWORD}"
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker push meetalodariya/client |
            fi

workflows:
  build-test-deploy:
    jobs:
      - build-deploy
