version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.0.0
        command:
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Build: Client"
          command: |
            docker build -t test/client -f ./client/Dockerfile.dev ./client
      - run:
          name: "Test: Client"
          command: |
            docker run -e CI=true test/client npm run test -- --coverage

  build-deploy:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # - run:
      #     name: "Build: Client"
      #     command: docker build ./client -t $DOCKERHUB_USERNAME/client:${COMMIT_HASH}
      # - run:
      #     name: "Build: Server"
      #     command: docker build ./client -t $DOCKERHUB_USERNAME/server:${COMMIT_HASH}
      # - run:
      #     name: "Build: Worker"
      #     command: docker build ./client -t $DOCKERHUB_USERNAME/worker:${COMMIT_HASH}
      - run:
          name: "Build: NGINX"
          command: |
            docker build ./client -t $DOCKERHUB_USERNAME/nginx:${CIRCLE_SHA1:0:8}
      - run:
          name: "Push images"
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker push $DOCKERHUB_USERNAME/nginx:${CIRCLE_SHA1:0:8}
            fi

workflows:
  build-test-deploy:
    jobs:
      - build-deploy
